set RABBITMQ_USER=isnr
set RABBITMQ_PASSWORD=isnr2019
set RABBITMQ_HOST=172.20.0.220
set RABBITMQ_PORT=5671
set RABBITMQ_VHOST=isnr
set RABBITMQ_BPMEXCHANGE=bpm
set RABBITMQ_QUEUENAME=bpm
python storedata.py

